### ISSUE TITLE
Adding tags with mc is not cumulative

### ISSUE THREAD

**Issue by asitemade4u** [cboettig/minioclient#12]
Hi Carl,
Me again, sorry about that ;o))) but it is for a great cause.

I just noticed something uncanny with the tags through `mc`:

Here is the reproducible code:

```bash
library(minioclient)
library(magrittr)
# Create a test bucket
bkttst <- paste0(sample(letters, 12, replace = TRUE), collapse = "") %>%
  paste0("play/play-", .)
minioclient::mc_mb(bkttst, verbose = TRUE)
# Create a test file, copy it to the test bucket
system(command = "touch /tmp/test.csv")
minioclient::mc_cp("/tmp/test.csv", bkttst, recursive = TRUE, verbose = TRUE)
# Create a 1st tag in the test file
thekey <- "tst1"
theval="test1"
minioclient::mc(command = glue::glue('tag set {bkttst}/test.csv "{thekey}={theval}"'))
# Create a 2nd tag in the test file
thekey <- "tst2"
theval <- "test2"
minioclient::mc(command = glue::glue('tag set {bkttst}/test.csv "{thekey}={theval}"'))
# Test the presence of the tags in the file
minioclient::mc(command = glue::glue("tag list {bkttst}/test.csv --recursive"))
```
The error is that only the SECOND tag is attached to the file, having erased the first one.

S.

**Comment by cboettig** [comment]
yup, the [official docs](https://min.io/docs/minio/linux/reference/minio-mc/mc-tag-set.html) are a bit vague on this too, but I think that's the expected behavior -- multiple tags must be set as a vector, you can't accumulate tags by setting them one at a time.  

Note that `mc tag remove` doesn't take an argument for which tag to remove, it just removes all tags, complementing the behavior of `tag set` to set all tags at once.  I think if `set` supported accumulating tags by adding them one-by-one, then `remove` would support removing tags one-by-one too.  I must agree with you that tt would be nice if the docs spelled that out of course :-)
